version: '3.1'

services:
  .graalvm-example:
    build:
      context: .
    volumes:
      - $PWD:$PWD
    working_dir: $PWD

  graalvm-example-22.3.3:
    extends:
      service: .graalvm-example
    build:
      context: .
      dockerfile: Dockerfile.22.3.3
    command: ./mvnw clean test -f pom.22.xml

  graalvm-example-jdk21:
    extends:
      service: .graalvm-example
    image: ghcr.io/graalvm/jdk-community:21
    command: ./mvnw clean test -f pom.jdk21.xml
