FROM ubuntu:20.04
ARG GRAALVM_VERSION="21.0.0"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --yes --no-install-recommends curl less locales tzdata maven wget

# Install GraalVM
RUN ARCH="$(uname -m | sed s/x86_64/x64/)" && \
    mkdir -p /usr/local/graalvm-${GRAALVM_VERSION} && \
    wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${GRAALVM_VERSION}/graalvm-community-jdk-${GRAALVM_VERSION}_linux-${ARCH}_bin.tar.gz -P /tmp && \
    tar -xvzf /tmp/graalvm-*.tar.gz -C /usr/local/graalvm-${GRAALVM_VERSION} --strip-components 1 && \
    rm /tmp/graalvm-*.tar.gz

ENV GRAALVM_HOME="/usr/local/graalvm-${GRAALVM_VERSION}"
ENV PATH="${GRAALVM_HOME}/bin:$PATH"
ENV JAVA_HOME=${GRAALVM_HOME}

ARG USERID="1000"
ARG USERNAME="test"
ARG USERHOME="/home/test"

RUN adduser --disabled-password --gecos "" --uid $USERID $USERNAME --home $USERHOME
RUN usermod $USERNAME -a -G sudo
RUN echo "$USERNAME     ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers
USER $USERNAME
