version: '3.1'

services:
  .graalvm-example:
    hostname: graalvm-example
    build:
      context: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - $PWD:$PWD
    working_dir: $PWD

  graalvm-example-22.3.3:
    extends:
      service: .graalvm-example
    image: ghcr.io/graalvm/graalvm-ce:ol7-java17-22.3.3

  graalvm-example-jdk21:
    extends:
      service: .graalvm-example
    image: ghcr.io/graalvm/jdk-community:21
